### ISSUE TITLE
MediaWiki 1.29 compatibility?

### ISSUE THREAD

**Issue by osnard** [marc-despland/MultiLanguageManager#1]
Hi,
very nice extension. Just a short question: the last commit was in May 2017. Can you tell if this version (1.0.1) is compatible to MediaWiki 1.29?

Best regards,
Robert

**Comment by osnard** [comment]
Answering my own question: No.
Thanks anyways

**Comment by marc-despland** [comment]
Sorry, no it's not ... i haven't work on this extension for a long time ... someone ask me few month ago to see how to update it ... but the mediawiki API has changed a lot  ... and i think the extension need to be entirely rewrite.
I just put it on github ... but I don't think I will have the time to do the job

**Comment by osnard** [comment]
Hi! My company will implement a new version called MultiLanguageManager2. It will be a complete rewrite (except for the database tables, so the software stays compatible). With your permission I'd change the name back to MultiLanguageManager and publish the work as GPL on mediawiki.org and within Wikimedia Git repos.

**Comment by marc-despland** [comment]
Yes of course ... it 's a great news 
when it's done give me the link and i will add a link to your version on this repo

fill free to modify the page on mediawiki web site too :)

**Comment by nemobis** [comment]
Added a question at https://meta.wikimedia.org/wiki/User_talk:Osnard

**Comment by osnard** [comment]
@marc-despland The code is not public available. I edited the extension description page on mw.org
@nemobis Thanks for the hint. I will answer on the talk page soon.
